services:
  python-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - neo4j
      - qdrant

  neo4j:
    image: neo4j:5.26
    container_name: echoroots_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - ../neo4j/data:/data
      - ../neo4j/logs:/logs

  qdrant:
    image: qdrant/qdrant:latest
    container_name: echoroots_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../qdrant/storage:/qdrant/storage